# Generated by Django 5.1.7 on 2025-04-01 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_hall', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyInfo',
            fields=[
                ('keyno', models.AutoField(db_column='KeyNo', db_comment='唯一标识符', primary_key=True, serialize=False)),
                ('company_name', models.CharField(db_column='Company_name', db_comment='公司名称', max_length=255)),
                ('company_birth', models.CharField(blank=True, db_column='Company_birth', db_comment='公司成立年份', max_length=64, null=True)),
                ('insured_num', models.CharField(blank=True, db_column='Insured_num', db_comment='参保人数', max_length=255, null=True)),
                ('latitude', models.CharField(blank=True, db_column='Latitude', db_comment='纬度', max_length=255, null=True)),
                ('longitude', models.CharField(blank=True, db_column='Longitude', db_comment='经度', max_length=255, null=True)),
                ('industry', models.CharField(blank=True, db_column='Industry', db_comment='公司所属产业', max_length=255, null=True)),
                ('province', models.CharField(blank=True, db_column='Province', db_comment='所在省份', max_length=255, null=True)),
                ('city', models.CharField(blank=True, db_column='City', db_comment='所在城市', max_length=255, null=True)),
                ('county', models.CharField(blank=True, db_column='County', db_comment='所在区县', max_length=255, null=True)),
            ],
            options={
                'db_table': 'company_info',
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='DataEntry',
        ),
    ]
