# Generated by Django 5.2 on 2025-04-05 07:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data_hall', '0002_companyinfo_delete_dataentry'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='companyinfo',
            options={'managed': True},
        ),
    ]
