# Generated by Django 5.1.7 on 2025-04-09 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_hall', '0003_alter_companyinfo_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='companyinfo',
            name='industry',
        ),
        migrations.AddField(
            model_name='companyinfo',
            name='company_scale',
            field=models.CharField(blank=True, db_column='Company_scale', db_comment='公司规模', max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='companyinfo',
            name='new_industry',
            field=models.CharField(blank=True, db_column='Industry', db_comment='公司所属产业', max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='companyinfo',
            name='new_industry_sub',
            field=models.CharField(blank=True, db_column='Industry_sub', db_comment='公司所属产业子类', max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='companyinfo',
            name='std_industr_big_category',
            field=models.CharField(blank=True, db_column='Std_industr_sub_category', db_comment='国标行业大类', max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='companyinfo',
            name='std_industr_category',
            field=models.CharField(blank=True, db_column='Std_industr_category', db_comment='国标行业门类', max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='companyinfo',
            name='std_industr_mid_category',
            field=models.CharField(blank=True, db_column='std_industr_mid_category', db_comment='国标行业中类', max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='companyinfo',
            name='std_industr_small_category',
            field=models.CharField(blank=True, db_column='std_industr_small_category', db_comment='国标行业小类', max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='companyinfo',
            name='tag',
            field=models.CharField(blank=True, db_column='tag', db_comment='标签', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='companyinfo',
            name='city',
            field=models.CharField(blank=True, db_column='City', db_comment='所在城市', max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='companyinfo',
            name='company_birth',
            field=models.CharField(blank=True, db_column='Company_birth', db_comment='公司成立年份', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='companyinfo',
            name='company_name',
            field=models.CharField(db_column='Company_name', db_comment='公司名称', max_length=128),
        ),
        migrations.AlterField(
            model_name='companyinfo',
            name='county',
            field=models.CharField(blank=True, db_column='County', db_comment='所在区县', max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='companyinfo',
            name='insured_num',
            field=models.CharField(blank=True, db_column='Insured_num', db_comment='参保人数', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='companyinfo',
            name='keyno',
            field=models.CharField(db_column='KeyNo', db_comment='唯一标识符', max_length=64, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='companyinfo',
            name='latitude',
            field=models.CharField(blank=True, db_column='Latitude', db_comment='纬度', max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='companyinfo',
            name='longitude',
            field=models.CharField(blank=True, db_column='Longitude', db_comment='经度', max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='companyinfo',
            name='province',
            field=models.CharField(blank=True, db_column='Province', db_comment='所在省份', max_length=20, null=True),
        ),
    ]
