# Generated by Django 5.1.7 on 2025-04-09 06:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data_hall', '0004_remove_companyinfo_industry_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='companyinfo',
            old_name='new_industry',
            new_name='industry',
        ),
        migrations.RenameField(
            model_name='companyinfo',
            old_name='new_industry_sub',
            new_name='industry_sub',
        ),
    ]
