# Generated by Django 5.1.7 on 2025-04-10 09:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_hall', '0005_rename_new_industry_companyinfo_industry_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyRanking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dev_potential', models.DecimalField(decimal_places=2, help_text='0-100分', max_digits=5, verbose_name='发展潜力')),
                ('expansion_speed', models.DecimalField(decimal_places=2, help_text='0-100分', max_digits=5, verbose_name='扩张速度')),
                ('innovation', models.DecimalField(decimal_places=2, help_text='0-100分', max_digits=5, verbose_name='创新能力')),
                ('capital_attention', models.DecimalField(decimal_places=2, help_text='0-100分', max_digits=5, verbose_name='资本关注')),
                ('team_background', models.DecimalField(decimal_places=2, help_text='0-100分', max_digits=5, verbose_name='团队背景')),
                ('comprehensive_score', models.DecimalField(decimal_places=2, help_text='0-100分', max_digits=5, verbose_name='综合得分')),
                ('rank', models.PositiveIntegerField(blank=True, null=True, verbose_name='排名')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('company', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ranking', to='data_hall.companyinfo', verbose_name='关联企业')),
            ],
            options={
                'verbose_name': '企业排名',
                'verbose_name_plural': '企业排名',
                'ordering': ['rank'],
            },
        ),
    ]
