# Generated by Django 5.1.7 on 2025-04-22 07:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_hall', '0006_companyranking'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyFinancing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('financing_round', models.CharField(blank=True, max_length=50, null=True, verbose_name='融资轮次')),
                ('financing_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, verbose_name='融资金额(万元)')),
                ('financing_date', models.DateField(blank=True, null=True, verbose_name='融资日期')),
                ('investor_id', models.CharField(blank=True, max_length=64, null=True, verbose_name='投资方ID')),
                ('investor_name', models.CharField(blank=True, max_length=128, null=True, verbose_name='投资方名称')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('company', models.ForeignKey(db_column='keyno', on_delete=django.db.models.deletion.CASCADE, related_name='financings', to='data_hall.companyinfo', verbose_name='关联企业')),
            ],
            options={
                'verbose_name': '企业融资情况',
                'verbose_name_plural': '企业融资情况',
                'ordering': ['-financing_date'],
                'indexes': [models.Index(fields=['company'], name='data_hall_c_keyno_5da0ec_idx'), models.Index(fields=['financing_date'], name='data_hall_c_financi_22946b_idx'), models.Index(fields=['financing_round'], name='data_hall_c_financi_a0463d_idx')],
            },
        ),
    ]
