# Generated by Django 5.1.7 on 2025-04-22 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_hall', '0007_companyfinancing'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyfinancing',
            name='financing_amount',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='融资金额'),
        ),
    ]
