# Generated by Django 5.1.7 on 2025-06-04 09:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_hall', '0008_alter_companyfinancing_financing_amount'),
    ]

    operations = [
        migrations.CreateModel(
            name='IndustryChain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='产业链名称')),
                ('code', models.CharField(help_text='例如：IC0076', max_length=20, unique=True, verbose_name='产业链代码')),
                ('description', models.TextField(blank=True, verbose_name='描述')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '产业链',
                'verbose_name_plural': '产业链',
                'db_table': 'industry_chain',
                'indexes': [models.Index(fields=['name'], name='industry_ch_name_812d96_idx'), models.Index(fields=['code'], name='industry_ch_code_943182_idx')],
            },
        ),
        migrations.CreateModel(
            name='ChainPoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='链点名称')),
                ('code', models.CharField(help_text='例如：IC0076001', max_length=20, unique=True, verbose_name='节点代码')),
                ('level', models.CharField(max_length=255, verbose_name='层级')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='data_hall.chainpoint', verbose_name='父链点')),
                ('industry_chain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chain_points', to='data_hall.industrychain', verbose_name='所属产业链')),
            ],
            options={
                'verbose_name': '链点',
                'verbose_name_plural': '链点',
                'db_table': 'chain_point',
            },
        ),
        migrations.CreateModel(
            name='ChainPointCompany',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('chain_point', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='companies', to='data_hall.chainpoint', verbose_name='链点')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chain_points', to='data_hall.companyinfo', verbose_name='公司')),
            ],
            options={
                'verbose_name': '链点-公司关联',
                'verbose_name_plural': '链点-公司关联',
                'db_table': 'chain_point_company',
                'indexes': [models.Index(fields=['chain_point', 'company'], name='chain_point_chain_p_f58984_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='chainpoint',
            index=models.Index(fields=['level'], name='chain_point_level_33fac5_idx'),
        ),
        migrations.AddIndex(
            model_name='chainpoint',
            index=models.Index(fields=['parent'], name='chain_point_parent__ebaf87_idx'),
        ),
        migrations.AddIndex(
            model_name='chainpoint',
            index=models.Index(fields=['code'], name='chain_point_code_fbb4b4_idx'),
        ),
    ]
