# Generated by Django 4.2.22 on 2025-06-13 09:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data_hall', '0009_industrychain_chainpoint_chainpointcompany_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Province',
            fields=[
                ('code', models.CharField(max_length=6, primary_key=True, serialize=False, unique=True, verbose_name='省份代码')),
                ('name', models.CharField(max_length=50, verbose_name='省份名称')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '省份',
                'verbose_name_plural': '省份',
                'db_table': 'province',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('code', models.CharField(max_length=6, primary_key=True, serialize=False, unique=True, verbose_name='城市代码')),
                ('name', models.CharField(max_length=50, verbose_name='城市名称')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('province', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cities', to='data_hall.province', verbose_name='所属省份')),
            ],
            options={
                'verbose_name': '城市',
                'verbose_name_plural': '城市',
                'db_table': 'city',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='District',
            fields=[
                ('code', models.CharField(max_length=6, primary_key=True, serialize=False, unique=True, verbose_name='区县代码')),
                ('name', models.CharField(max_length=50, verbose_name='区县名称')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='districts', to='data_hall.city', verbose_name='所属城市')),
            ],
            options={
                'verbose_name': '区县',
                'verbose_name_plural': '区县',
                'db_table': 'district',
                'ordering': ['code'],
                'indexes': [models.Index(fields=['city'], name='district_city_id_40ce18_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='city',
            index=models.Index(fields=['province'], name='city_provinc_4c6d0a_idx'),
        ),
    ]
