# Generated by Django 4.2.22 on 2025-06-13 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_hall', '0010_province_city_district_city_city_provinc_4c6d0a_idx'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city',
            name='code',
            field=models.CharField(max_length=10, primary_key=True, serialize=False, unique=True, verbose_name='城市代码'),
        ),
        migrations.AlterField(
            model_name='city',
            name='name',
            field=models.CharField(max_length=100, verbose_name='城市名称'),
        ),
        migrations.AlterField(
            model_name='district',
            name='code',
            field=models.CharField(max_length=10, primary_key=True, serialize=False, unique=True, verbose_name='区县代码'),
        ),
        migrations.AlterField(
            model_name='district',
            name='name',
            field=models.CharField(max_length=100, verbose_name='区县名称'),
        ),
        migrations.AlterField(
            model_name='province',
            name='code',
            field=models.CharField(max_length=10, primary_key=True, serialize=False, unique=True, verbose_name='省份代码'),
        ),
        migrations.AlterField(
            model_name='province',
            name='name',
            field=models.CharField(max_length=100, verbose_name='省份名称'),
        ),
    ]
