# Generated by Django 4.2.22 on 2025-06-19 01:55

from django.db import migrations
from django.contrib.auth.hashers import make_password


def migrate_users_to_django_auth(apps, schema_editor):
    """Migrate custom User model data to Django's User model"""
    CustomUser = apps.get_model('data_hall', 'User')
    DjangoUser = apps.get_model('auth', 'User')
    
    # Migrate existing users
    for custom_user in CustomUser.objects.all():
        # Check if Django user already exists
        if not DjangoUser.objects.filter(username=custom_user.username).exists():
            # Create Django user with hashed password
            django_user = DjangoUser.objects.create(
                username=custom_user.username,
                email=custom_user.email,
                password=make_password(custom_user.password),  # Hash the plain text password
                date_joined=custom_user.created_at,
                is_active=True
            )
            print(f"Migrated user: {custom_user.username}")


def reverse_migrate_users(apps, schema_editor):
    """Reverse migration - not recommended in production"""
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('data_hall', '0011_alter_city_code_alter_city_name_alter_district_code_and_more'),
        ('auth', '0012_alter_user_first_name_max_length'),  # Ensure Django auth migrations are run
    ]

    operations = [
        migrations.RunPython(migrate_users_to_django_auth, reverse_migrate_users),
    ]
