# Generated by Django 4.2.22 on 2025-06-20 01:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data_hall', '0012_migrate_to_django_auth'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
