# Generated by Django 5.1.7 on 2025-06-23 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_hall', '0012_migrate_to_django_auth'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='chainpointcompany',
            name='chain_point_chain_p_f58984_idx',
        ),
        migrations.AddField(
            model_name='chainpointcompany',
            name='level',
            field=models.IntegerField(help_text='所在层级', null=True, verbose_name='层级'),
        ),
        migrations.AddField(
            model_name='chainpointcompany',
            name='node_importance',
            field=models.IntegerField(help_text='节点重要性(0-5)', null=True, verbose_name='节点重要性'),
        ),
        migrations.AddField(
            model_name='chainpointcompany',
            name='node_type',
            field=models.IntegerField(help_text='节点类型(1或2)', null=True, verbose_name='节点类型'),
        ),
        migrations.AddField(
            model_name='chainpointcompany',
            name='score',
            field=models.DecimalField(decimal_places=2, help_text='企业与该链点的关联分数', max_digits=5, null=True, verbose_name='关联分数'),
        ),
        migrations.AddIndex(
            model_name='chainpointcompany',
            index=models.Index(fields=['score'], name='idx_cpc_score'),
        ),
        migrations.AddIndex(
            model_name='chainpointcompany',
            index=models.Index(fields=['node_type'], name='idx_cpc_node_type'),
        ),
        migrations.AddIndex(
            model_name='chainpointcompany',
            index=models.Index(fields=['level'], name='idx_cpc_level'),
        ),
        migrations.AddIndex(
            model_name='chainpointcompany',
            index=models.Index(fields=['chain_point', 'score'], name='idx_cpc_point_score'),
        ),
        migrations.AddIndex(
            model_name='chainpointcompany',
            index=models.Index(fields=['company', 'score'], name='idx_cpc_company_score'),
        ),
        migrations.AddIndex(
            model_name='chainpointcompany',
            index=models.Index(fields=['level', 'node_type'], name='idx_cpc_level_type'),
        ),
    ]
