# Generated by Django 4.2.22 on 2025-06-23 02:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('data_hall', '0013_delete_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('user', '用户'), ('assistant', 'AI助手'), ('system', '系统')], default='user', max_length=20, verbose_name='角色')),
                ('content', models.TextField(verbose_name='消息内容')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('session_id', models.CharField(blank=True, help_text='用于标识同一会话的消息', max_length=100, null=True, verbose_name='会话ID')),
                ('metadata', models.JSONField(blank=True, help_text='存储额外的消息元数据，如模型版本、耗时等', null=True, verbose_name='元数据')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_messages', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '聊天消息',
                'verbose_name_plural': '聊天消息',
                'db_table': 'chat_message',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', '-created_at'], name='chat_messag_user_id_ce6f7a_idx'), models.Index(fields=['user', 'role'], name='chat_messag_user_id_cd9c64_idx'), models.Index(fields=['session_id'], name='chat_messag_session_389d44_idx'), models.Index(fields=['-created_at'], name='chat_messag_created_f18bb8_idx')],
            },
        ),
    ]
