# Generated by Django 4.2.22 on 2025-06-24 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_hall', '0014_chatmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='chainpoint',
            name='company_count',
            field=models.IntegerField(default=0, help_text='该链点关联的企业数量', verbose_name='企业数量'),
        ),
        migrations.AddField(
            model_name='chainpoint',
            name='node_important',
            field=models.IntegerField(blank=True, help_text='0-5级重要程度', null=True, verbose_name='重要程度'),
        ),
        migrations.AddField(
            model_name='chainpoint',
            name='node_num',
            field=models.IntegerField(blank=True, null=True, verbose_name='节点序号'),
        ),
        migrations.AddField(
            model_name='chainpoint',
            name='node_num_desc',
            field=models.CharField(blank=True, help_text='如：上游、中游、下游', max_length=100, null=True, verbose_name='节点描述'),
        ),
        migrations.AddField(
            model_name='chainpoint',
            name='node_type',
            field=models.IntegerField(blank=True, help_text='1=分类节点, 2=产品节点, 3=下游应用', null=True, verbose_name='节点类型'),
        ),
        migrations.AddField(
            model_name='chainpoint',
            name='parent_node_code',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='父节点代码'),
        ),
        migrations.AddField(
            model_name='chainpoint',
            name='product_code',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='产品代码'),
        ),
        migrations.AddField(
            model_name='chainpoint',
            name='product_define',
            field=models.TextField(blank=True, null=True, verbose_name='产品定义'),
        ),
        migrations.AddField(
            model_name='chainpoint',
            name='product_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='产品名称'),
        ),
        migrations.AddIndex(
            model_name='chainpoint',
            index=models.Index(fields=['node_type'], name='chain_point_node_ty_c1f5a5_idx'),
        ),
        migrations.AddIndex(
            model_name='chainpoint',
            index=models.Index(fields=['node_important'], name='chain_point_node_im_2ec9e8_idx'),
        ),
    ]
