# Generated by Django 4.2.22 on 2025-06-26 08:24

from django.db import migrations, models


def safe_remove_index(apps, schema_editor, table_name, index_name):
    """安全删除索引 - 只有索引存在时才删除"""
    with schema_editor.connection.cursor() as cursor:
        # 检查索引是否存在
        cursor.execute("""
            SELECT COUNT(*) 
            FROM information_schema.statistics 
            WHERE table_schema = DATABASE() 
            AND table_name = %s 
            AND index_name = %s
        """, [table_name, index_name])
        
        if cursor.fetchone()[0] > 0:
            # 索引存在，删除它
            cursor.execute(f"DROP INDEX `{index_name}` ON `{table_name}`")


def safe_add_field(apps, schema_editor, table_name, field_name, field_sql):
    """安全添加字段 - 只有当字段不存在时才添加"""
    with schema_editor.connection.cursor() as cursor:
        # 检查字段是否存在
        cursor.execute("""
            SELECT COUNT(*) 
            FROM information_schema.columns 
            WHERE table_schema = DATABASE() 
            AND table_name = %s 
            AND column_name = %s
        """, [table_name, field_name])
        
        if cursor.fetchone()[0] == 0:
            # 字段不存在，添加它
            cursor.execute(f"ALTER TABLE `{table_name}` ADD COLUMN {field_sql}")


def safe_remove_field(apps, schema_editor, table_name, field_name):
    """安全删除字段 - 只有当字段存在时才删除"""
    with schema_editor.connection.cursor() as cursor:
        # 检查字段是否存在
        cursor.execute("""
            SELECT COUNT(*) 
            FROM information_schema.columns 
            WHERE table_schema = DATABASE() 
            AND table_name = %s 
            AND column_name = %s
        """, [table_name, field_name])
        
        if cursor.fetchone()[0] > 0:
            # 字段存在，删除它
            cursor.execute(f"ALTER TABLE `{table_name}` DROP COLUMN `{field_name}`")


def safe_add_index(apps, schema_editor, table_name, index_name, index_sql):
    """安全添加索引 - 只有当索引不存在时才添加"""
    with schema_editor.connection.cursor() as cursor:
        # 检查索引是否存在
        cursor.execute("""
            SELECT COUNT(*) 
            FROM information_schema.statistics 
            WHERE table_schema = DATABASE() 
            AND table_name = %s 
            AND index_name = %s
        """, [table_name, index_name])
        
        if cursor.fetchone()[0] == 0:
            # 索引不存在，添加它
            cursor.execute(index_sql)


def migrate_forward(apps, schema_editor):
    """前向迁移 - 执行所有更改"""
    
    # 1. 安全删除索引
    safe_remove_index(apps, schema_editor, 'chain_point', 'chain_point_node_ty_c1f5a5_idx')
    safe_remove_index(apps, schema_editor, 'chain_point', 'chain_point_node_im_2ec9e8_idx')
    safe_remove_index(apps, schema_editor, 'chain_point_company', 'chain_point_chain_p_f58984_idx')
    
    # 2. 安全删除 ChainPoint 表中的字段
    safe_remove_field(apps, schema_editor, 'chain_point', 'company_count')
    safe_remove_field(apps, schema_editor, 'chain_point', 'node_important')
    safe_remove_field(apps, schema_editor, 'chain_point', 'node_num')
    safe_remove_field(apps, schema_editor, 'chain_point', 'node_num_desc')
    safe_remove_field(apps, schema_editor, 'chain_point', 'node_type')
    safe_remove_field(apps, schema_editor, 'chain_point', 'parent_node_code')
    safe_remove_field(apps, schema_editor, 'chain_point', 'product_code')
    safe_remove_field(apps, schema_editor, 'chain_point', 'product_define')
    safe_remove_field(apps, schema_editor, 'chain_point', 'product_name')
    
    # 3. 安全添加 ChainPointCompany 表中的字段
    safe_add_field(apps, schema_editor, 'chain_point_company', 'level', 
                   "`level` int DEFAULT NULL COMMENT '所在层级'")
    safe_add_field(apps, schema_editor, 'chain_point_company', 'node_importance', 
                   "`node_importance` int DEFAULT NULL COMMENT '节点重要性(0-5)'")
    safe_add_field(apps, schema_editor, 'chain_point_company', 'node_type', 
                   "`node_type` int DEFAULT NULL COMMENT '节点类型(1或2)'")
    safe_add_field(apps, schema_editor, 'chain_point_company', 'score', 
                   "`score` decimal(5,2) DEFAULT NULL COMMENT '企业与该链点的关联分数'")
    
    # 4. 安全添加新索引
    safe_add_index(apps, schema_editor, 'chain_point_company', 'idx_cpc_score',
                   "CREATE INDEX `idx_cpc_score` ON `chain_point_company` (`score`)")
    safe_add_index(apps, schema_editor, 'chain_point_company', 'idx_cpc_node_type',
                   "CREATE INDEX `idx_cpc_node_type` ON `chain_point_company` (`node_type`)")
    safe_add_index(apps, schema_editor, 'chain_point_company', 'idx_cpc_level',
                   "CREATE INDEX `idx_cpc_level` ON `chain_point_company` (`level`)")
    safe_add_index(apps, schema_editor, 'chain_point_company', 'idx_cpc_point_score',
                   "CREATE INDEX `idx_cpc_point_score` ON `chain_point_company` (`chain_point_id`, `score`)")
    safe_add_index(apps, schema_editor, 'chain_point_company', 'idx_cpc_company_score',
                   "CREATE INDEX `idx_cpc_company_score` ON `chain_point_company` (`company_id`, `score`)")
    safe_add_index(apps, schema_editor, 'chain_point_company', 'idx_cpc_level_type',
                   "CREATE INDEX `idx_cpc_level_type` ON `chain_point_company` (`level`, `node_type`)")


def migrate_reverse(apps, schema_editor):
    """反向迁移 - 回滚更改"""
    pass  # 不实现反向操作，因为这是数据库结构修复


class Migration(migrations.Migration):

    dependencies = [
        ('data_hall', '0015_chainpoint_company_count_chainpoint_node_important_and_more'),
    ]

    operations = [
        migrations.RunPython(
            migrate_forward,
            migrate_reverse,
        ),
    ]
