# Generated by Django 5.1.7 on 2025-10-22 06:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data_hall', '0013_remove_chainpointcompany_chain_point_chain_p_f58984_idx_and_more'),
        ('data_hall', '0016_remove_chainpoint_chain_point_node_ty_c1f5a5_idx_and_more'),
    ]

    operations = [
    ]
